---
name: Octopus MinMax Bot
image: eelmafia/octopus-minmax-bot
url: https://github.com/eelmafia/octopus-minmax
ingress: true
ingress_port: 5050
ports:
  5050/tcp: null
ports_description:
  5050/tcp: Web UI (optional external access)
webui: http://[HOST]:[PORT:5050]/
version: v1.0.7
slug: octopus_minmax_bot
startup: application
init: false
legacy: true
description: A bot to automatically compare and switch smart electricity tariffs on Octopus Energy
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
options:
  API_KEY: "API KEY HERE"
  ACC_NUMBER: "ACC NUMBER HERE"
  EXECUTION_TIME: "23:00"
  SWITCH_THRESHOLD: 2
  ONE_OFF: false
  DRY_RUN: false
  NOTIFICATION_URLS: ""
  TARIFFS: "agile,go,flexible"
  TZ: "Europe/London"
  BATCH_NOTIFICATIONS: false
  WEB_USERNAME: "admin"
  WEB_PASSWORD: "admin"
schema:
  API_KEY: str
  ACC_NUMBER: str
  EXECUTION_TIME: str
  SWITCH_THRESHOLD: int
  ONE_OFF: bool
  DRY_RUN: bool
  NOTIFICATION_URLS: str
  TARIFFS: str
  TZ: str
  BATCH_NOTIFICATIONS: bool
  WEB_USERNAME: str
  WEB_PASSWORD: password
