---
name: Octopus MinMax Bot
image: eelmafia/octopus-minmax-bot
url: https://github.com/eelmafia/octopus-minmax
ingress: true
ingress_port: 5050
ports:
  5050/tcp: null
ports_description:
  5050/tcp: Web UI (optional external access)
webui: http://[HOST]:[PORT:5050]/
version: v1.0.5
slug: octopus_minmax_bot
startup: application
init: false
map:
  - addon_config:rw
  - ssl:ro
description: |
  A bot to automatically compare and switch smart electricity tariffs on Octopus Energy.

  Refer to documentation at: [github.com/eelmafia/octopus-minmax](https://github.com/eelmafia/octopus-minmax)

  **Deprecation Notice**

  This *settings page* will be removed in a later release. After the app is started, the settings
  below are copied to the config.json file which can be accessed under the /addon_configs folder
  in Home Assistant.
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
options:
  OCTOBOT_CONFIG_PATH: "/config/config.json"
  API_KEY: "API KEY HERE"
  ACC_NUMBER: "ACC NUMBER HERE"
  BASE_URL: "https://api.octopus.energy/v1"
  EXECUTION_TIME: "23:00"
  SWITCH_THRESHOLD: 2
  ONE_OFF: false
  DRY_RUN: false
  NOTIFICATION_URLS: ""
  ONLY_RESULTS_NOTIFICATIONS: false
  TARIFFS: "agile,go,flexible"
  TZ: "Europe/London"
  BATCH_NOTIFICATIONS: false
  MQTT_ENABLED: false
  MQTT_HOST: "core-mosquitto"
  MQTT_PORT: 1883
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  MQTT_TOPIC: ""
  MQTT_USE_TLS: false
  MQTT_TLS_INSECURE: false
  MQTT_CA_CERT: ""
  MQTT_CLIENT_CERT: ""
  MQTT_CLIENT_KEY: ""
  WEB_USERNAME: "admin"
  WEB_PASSWORD: "admin"
  WEB_PORT: 5050
schema:
  OCTOBOT_CONFIG_PATH: str
  API_KEY: str
  ACC_NUMBER: str
  BASE_URL: str
  EXECUTION_TIME: str
  SWITCH_THRESHOLD: float
  ONE_OFF: bool
  DRY_RUN: bool
  NOTIFICATION_URLS: str
  ONLY_RESULTS_NOTIFICATIONS: bool
  TARIFFS: str
  TZ: str
  BATCH_NOTIFICATIONS: bool
  MQTT_ENABLED: bool
  MQTT_HOST: str
  MQTT_PORT: int
  MQTT_USERNAME: str
  MQTT_PASSWORD: password
  MQTT_TOPIC: str
  MQTT_USE_TLS: bool
  MQTT_TLS_INSECURE: bool
  MQTT_CA_CERT: str
  MQTT_CLIENT_CERT: str
  MQTT_CLIENT_KEY: str
  WEB_USERNAME: str
  WEB_PASSWORD: password
  WEB_PORT: int
