---
name: Octopus MinMax Bot
build:
  dockerfile: dockerfile
url: https://github.com/eelmafia/octopus-minmax
ingress: true
ingress_port: 5050
ports:
  5050/tcp: null
ports_description:
  5050/tcp: Web UI (optional external access)
webui: http://[HOST]:[PORT:5050]/
version: v1.0.5
slug: octopus_minmax_bot
startup: application
init: false
map:
  - addon_config:rw
  - ssl:ro
description: A bot to automatically compare and switch smart electricity tariffs on Octopus Energy
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
